name: _finance_tracking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.9.1
  get_storage: ^2.1.1
  gap: ^3.0.1
  icons_plus: ^5.0.0
  syncfusion_flutter_charts: ^25.2.5
  persistent_bottom_nav_bar_v2: ^5.2.3

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

